name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          # test  application here

      - name: Build and Push Docker Image
        run: |
          # Add commands to build and push your Docker image here
