name: CD

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Build Docker image
        run: docker build -t my-helloworld .

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker tag my-helloworld docker.pkg.github.com/${{ github.repository }}/${{ github.run_number }}
          docker push docker.pkg.github.com/${{ github.repository }}/${{ github.run_number }}
